__default__: 
  h_vmem: 1G
  mem_free: 1G
  m_mem_free: 1G
demultiplex: 
  h_vmem: 1G
  mem_free: 1G
  m_mem_free: 1G
illqc: 
  h_vmem: 1G
  mem_free: 1G
  m_mem_free: 1G
stitch_reads: 
  h_vmem: 1G
  mem_free: 1G
  m_mem_free: 1G
decontam_phix_unassembled: 
  h_vmem: 1G
  mem_free: 1G
  m_mem_free: 1G
decontam_phix_assembled:
  h_vmem: 1G
  mem_free: 1G
  m_mem_free: 1G
decontam_host_unassembled:
  h_vmem: 1G
  mem_free: 1G
  m_mem_free: 1G
decontam_host_assembled:
  h_vmem: 1G
  mem_free: 1G
  m_mem_free: 1G
