# directory for the project; we don't really touch this
projdir: /mnt/isilon/microbiome/Hiseq01/XX/Data/Intensities/BaseCalls    
# todo: transfer from isilon to lustre; gunzip; merge; 

admins: zhaocy.dut@gmail.com      # to receive notification of success or fail
tmpdir: /mnt/lustre/users/zhaoc1/test   # for some tools to create temporary files

load_shotgun_pipeline_environment: source activate shotgun-pipeline


# customized settings for a project ---- START
data_dir: /mnt/lustre/users/zhaoc1/largefiles/test
lane_num: "001"
barcodes: "barcodes.txt"
# customized settings for a project ---- DONE

report:
    illqc: illqc_reports

output: # subdirectories in data_dir
    dnabc: dnabc_results
    illqc: illqc_results
    stitch: stitch_results
    decontam_phix_unassembled: decontam_phix_unassembled_results
    decontam_phix_assembled: decontam_phix_assembled_results
    decontam_host_unassembled: decontam_host_unassembled_results
    decontam_host_assembled: decontam_host_assembled_results
    kraken_classify_unassembled: kraken_classify_unassembled_results
    kraken_classify_assembled: kraken_classify_assembled_results

## parameters for each rules
stitch:
    memory: 1G
kraken:
    db: /mnt/isilon/microbiome/biodata/krakendb/viruses
